# Generated by Django 3.1.4 on 2021-01-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='questionaire_answered',
            field=models.BooleanField(default=False),
        ),
    ]
