# Generated by Django 3.1.4 on 2021-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0004_auto_20210104_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Address 2'),
        ),
    ]
