# Generated by Django 3.1.4 on 2021-01-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0005_auto_20210104_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='user_agreemenet',
            field=models.BooleanField(default=False),
        ),
    ]
