# Generated by Django 3.1.4 on 2021-01-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0006_user_profile_user_agreemenet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user_agreemenet',
            new_name='user_agreement',
        ),
    ]
