# Generated by Django 3.1.4 on 2021-01-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0008_auto_20210105_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='company_name',
            field=models.CharField(default='', max_length=255, verbose_name='Last Name'),
        ),
    ]
