# Generated by Django 3.1.4 on 2021-01-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0009_user_profile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='company_name',
            field=models.CharField(default='', max_length=255, verbose_name='Company Name'),
        ),
    ]
