# Generated by Django 3.1.4 on 2021-01-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0010_auto_20210105_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='questionaire_answered',
        ),
    ]
