# Generated by Django 3.1.4 on 2021-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0011_remove_user_profile_questionaire_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='company_industry',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('LGC', 'Logistics'), ('AGR', 'Agriculture')], default='', max_length=50, verbose_name='Company Industry'),
        ),
    ]
