# Generated by Django 3.1.4 on 2021-01-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0012_user_profile_company_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255, verbose_name='Industry Name')),
            ],
        ),
    ]
