# Generated by Django 3.1.4 on 2021-01-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0013_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='company_industry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='Maia.industries', verbose_name='Company Industry'),
        ),
    ]
