# Generated by Django 3.1.4 on 2021-01-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0014_auto_20210105_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='company_industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.industries', verbose_name='Company Industry'),
        ),
    ]
