# Generated by Django 3.1.4 on 2021-01-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0015_auto_20210105_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_financial_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField()),
                ('net_profit', models.FloatField()),
                ('expenses', models.FloatField()),
                ('return_on_equity', models.FloatField()),
                ('firm_value', models.FloatField()),
                ('debt', models.FloatField()),
                ('equity', models.FloatField()),
                ('return_on_asset', models.FloatField()),
                ('return_on_investment', models.FloatField()),
                ('networking_capital', models.FloatField()),
                ('spending_on_research', models.FloatField()),
                ('property_plant_equipment', models.FloatField()),
                ('cash_flow', models.FloatField()),
                ('goodwill', models.FloatField()),
                ('total_assets', models.FloatField()),
                ('total_liabilities', models.FloatField()),
                ('current_ratio', models.FloatField()),
                ('quick_ratio', models.FloatField()),
                ('cash_ratio', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maia.user_profile')),
            ],
        ),
    ]
