# Generated by Django 3.1.4 on 2021-01-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0016_user_financial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_financial_data',
            name='quater',
            field=models.CharField(choices=[('Q2', 'Quater 2'), ('Q1', 'Quater 1'), ('Q4', 'Quater 4'), ('Q3', 'Quater 3')], default=1, max_length=3, verbose_name='Quater'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='cash_flow',
            field=models.FloatField(verbose_name='Cash Flow'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='cash_ratio',
            field=models.FloatField(verbose_name='Cash Ratio'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='current_ratio',
            field=models.FloatField(verbose_name='Current Ratio'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='debt',
            field=models.FloatField(verbose_name='Debt'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='equity',
            field=models.FloatField(verbose_name='Equity'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='expenses',
            field=models.FloatField(verbose_name='Expenses'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='firm_value',
            field=models.FloatField(verbose_name='Firm Value'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='goodwill',
            field=models.FloatField(verbose_name='Goodwill'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='net_profit',
            field=models.FloatField(verbose_name='Net Profit'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='networking_capital',
            field=models.FloatField(verbose_name='Networking Capital'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='property_plant_equipment',
            field=models.FloatField(verbose_name='Property Plant Equipment'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='quick_ratio',
            field=models.FloatField(verbose_name='Quick Ratio'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='return_on_asset',
            field=models.FloatField(verbose_name='Return On Asset'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='return_on_equity',
            field=models.FloatField(verbose_name='Return On Equity'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='return_on_investment',
            field=models.FloatField(verbose_name='Return On Investment'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='revenue',
            field=models.FloatField(verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='spending_on_research',
            field=models.FloatField(verbose_name='Spending On Research'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='total_assets',
            field=models.FloatField(verbose_name='Total Assets'),
        ),
        migrations.AlterField(
            model_name='user_financial_data',
            name='total_liabilities',
            field=models.FloatField(verbose_name='Total Liabilities'),
        ),
    ]
