# Generated by Django 3.1.4 on 2021-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0017_auto_20210106_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_financial_data',
            name='quater',
            field=models.CharField(choices=[('Q1', 'Quater 1'), ('Q4', 'Quater 4'), ('Q3', 'Quater 3'), ('Q2', 'Quater 2')], default=1, max_length=3, verbose_name='Quater'),
        ),
    ]
