# Generated by Django 3.1.4 on 2021-01-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0018_auto_20210106_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_financial_data',
            name='quater',
            field=models.CharField(choices=[('Q4', 'Quater 4'), ('Q1', 'Quater 1'), ('Q2', 'Quater 2'), ('Q3', 'Quater 3')], default=1, max_length=3, verbose_name='Quater'),
        ),
    ]
