# Generated by Django 3.1.4 on 2021-01-06 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0020_auto_20210106_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_financial_data',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
