# Generated by Django 3.1.4 on 2021-01-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0021_user_financial_data_created_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_financial_data',
            name='quater',
            field=models.CharField(max_length=255, verbose_name='Quater'),
        ),
    ]
