# Generated by Django 3.1.4 on 2021-01-08 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0024_auto_20210108_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='tag',
        ),
    ]
