# Generated by Django 3.1.4 on 2021-01-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0025_remove_user_profile_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tags', verbose_name='Tag'),
        ),
    ]
