# Generated by Django 3.1.4 on 2021-01-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0026_user_profile_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='tag',
        ),
    ]
