# Generated by Django 3.1.4 on 2021-01-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0027_remove_user_profile_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
