# Generated by Django 3.1.4 on 2021-01-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0028_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
