# Generated by Django 3.1.4 on 2021-01-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0030_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag',
        ),
    ]
