# Generated by Django 3.1.4 on 2021-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0032_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
    ]
