# Generated by Django 3.1.4 on 2021-01-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0033_auto_20210109_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tag',
        ),
    ]
