# Generated by Django 3.1.4 on 2021-01-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0034_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='Description')),
            ],
        ),
    ]
