# Generated by Django 3.1.4 on 2021-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0035_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='tag',
            field=models.ManyToManyField(default=1, to='Maia.tag', verbose_name='Tag'),
        ),
    ]
