# Generated by Django 3.1.4 on 2021-01-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0037_advices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advices',
            name='Text',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
        migrations.CreateModel(
            name='Network_Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Skills', models.CharField(max_length=255)),
                ('URL', models.CharField(max_length=255)),
                ('tag', models.ManyToManyField(default=1, to='Maia.tag', verbose_name='Tag')),
            ],
        ),
    ]
