# Generated by Django 3.1.4 on 2021-01-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('Maia', '0040_recommandation_articles_recommandation_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djstripe.charge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maia.user_profile')),
            ],
        ),
    ]
