# Generated by Django 3.1.4 on 2021-01-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0041_user_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_payment',
            name='payment_record',
            field=models.CharField(max_length=255, verbose_name='Payment Record'),
        ),
    ]
