# Generated by Django 3.1.4 on 2021-01-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_2_4'),
        ('Maia', '0042_auto_20210109_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_payment',
            name='payment_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='djstripe.charge'),
        ),
    ]
