# Generated by Django 3.1.4 on 2021-01-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0043_auto_20210110_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchased_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateTimeField(auto_now_add=True, verbose_name='Purchased Date')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maia.user_profile')),
            ],
        ),
    ]
