# Generated by Django 3.1.4 on 2021-01-17 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0044_purchased_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_financial_data_v2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('q1_revenue', models.FloatField(verbose_name='Q1 Revenue')),
                ('q1_profit_before_tax', models.FloatField(verbose_name='Q1 Profit Before Tax')),
                ('q1_net_profit', models.FloatField(verbose_name='Q1 Net Profit')),
                ('q2_revenue', models.FloatField(verbose_name='Q2 Revenue')),
                ('q2_profit_before_tax', models.FloatField(verbose_name='Q2 Profit Before Tax')),
                ('q2_net_profit', models.FloatField(verbose_name='Q2 Net Profit')),
                ('q3_revenue', models.FloatField(verbose_name='Q3 Revenue')),
                ('q3_profit_before_tax', models.FloatField(verbose_name='Q3 Profit Before Tax')),
                ('q3_net_profit', models.FloatField(verbose_name='Q3 Net Profit')),
                ('q4_revenue', models.FloatField(verbose_name='Q4 Revenue')),
                ('q4_profit_before_tax', models.FloatField(verbose_name='Q4 Profit Before Tax')),
                ('q4_net_profit', models.FloatField(verbose_name='Q4 Net Profit')),
                ('yearly_revenue', models.FloatField(verbose_name='Yearly Revenue')),
                ('yearly_net_profit', models.FloatField(verbose_name='Yearly Net Profit')),
                ('net_tangeble_asset', models.FloatField(verbose_name='Net Tangeble Asset')),
                ('cash', models.FloatField(verbose_name='Cash')),
                ('debt', models.FloatField(verbose_name='Debt')),
                ('total_debt', models.FloatField(verbose_name='Total Debt')),
                ('current_ratio', models.FloatField(verbose_name='Current Ratio')),
                ('cash_ratio', models.FloatField(verbose_name='Cash Ratio')),
                ('return_on_asset', models.FloatField(verbose_name='Return On Assest')),
                ('asset_turn_over_ratio', models.FloatField(verbose_name='Asset Turn Over Ratio')),
                ('debt_to_asset_ratio', models.FloatField(verbose_name='Debt To Asset Ratio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maia.user_profile')),
            ],
        ),
        migrations.DeleteModel(
            name='user_financial_data',
        ),
    ]
