# Generated by Django 3.1.4 on 2021-01-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0045_auto_20210117_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='quick_ratio',
            field=models.FloatField(default=0, verbose_name='Quick Ratio'),
            preserve_default=False,
        ),
    ]
