# Generated by Django 3.1.4 on 2021-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0046_user_financial_data_v2_quick_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='net_assets',
            field=models.FloatField(default=0, verbose_name='Net Assets'),
            preserve_default=False,
        ),
    ]
