# Generated by Django 3.1.4 on 2021-01-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0047_user_financial_data_v2_net_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_financial_data_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_result', models.FloatField(verbose_name='Profit Result')),
                ('asset_result', models.FloatField(verbose_name='Asset Result')),
                ('cash_result', models.FloatField(verbose_name='Cash Result')),
                ('liquidity_result', models.FloatField(verbose_name='Liquidity Result')),
                ('general_result', models.FloatField(verbose_name='General Result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maia.user_profile')),
            ],
        ),
    ]
