# Generated by Django 3.1.4 on 2021-01-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0048_user_financial_data_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advices',
            name='tag',
        ),
        migrations.AddField(
            model_name='advices',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Maia.tag', verbose_name='Tag'),
        ),
    ]
