# Generated by Django 3.1.4 on 2021-01-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0050_auto_20210118_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommandation_video',
            name='URL',
        ),
    ]
