# Generated by Django 3.1.4 on 2021-01-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0051_remove_recommandation_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag_profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('desc', models.CharField(default='', max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='advices',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='network_suggestions',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recommandation_articles',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='recommandation_video',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='tag',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
