# Generated by Django 3.1.4 on 2021-01-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0052_auto_20210118_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag_profit',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
    ]
