# Generated by Django 3.1.4 on 2021-01-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0053_auto_20210118_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
    ]
