# Generated by Django 3.1.4 on 2021-01-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0054_user_profile_profit_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='advices',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
        migrations.AddField(
            model_name='network_suggestions',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
        migrations.AddField(
            model_name='recommandation_articles',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
        migrations.AddField(
            model_name='recommandation_video',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
    ]
