# Generated by Django 3.1.4 on 2021-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0057_auto_20210118_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network_suggestions',
            name='Skills',
            field=models.TextField(),
        ),
    ]
