# Generated by Django 3.1.4 on 2021-01-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0058_auto_20210118_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='network_suggestions',
            name='thumbnails',
            field=models.TextField(blank=True),
        ),
    ]
