# Generated by Django 3.1.4 on 2021-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0060_auto_20210118_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='cash_turnover_ratio',
            field=models.FloatField(default=0, verbose_name='Cash Turnover Ratio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='q1_net_profit_margin',
            field=models.FloatField(default=0, verbose_name='Q1 Net Profit Margin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='q2_net_profit_margin',
            field=models.FloatField(default=0, verbose_name='Q2 Net Profit Margin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='q3_net_profit_margin',
            field=models.FloatField(default=0, verbose_name='Q3 Net Profit Margin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='q4_net_profit_margin',
            field=models.FloatField(default=0, verbose_name='Q4 Net Profit Margin'),
            preserve_default=False,
        ),
    ]
