# Generated by Django 3.1.4 on 2021-01-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0061_auto_20210119_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='yearly_net_profit_margin',
            field=models.FloatField(default=0, verbose_name='Yearly Net Profit Margin'),
            preserve_default=False,
        ),
    ]
