# Generated by Django 3.1.4 on 2021-01-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0062_user_financial_data_v2_yearly_net_profit_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='tag_cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='tag_liquidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
            ],
        ),
    ]
