# Generated by Django 3.1.4 on 2021-01-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0063_tag_asset_tag_cash_tag_liquidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='advices',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AddField(
            model_name='advices',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AddField(
            model_name='advices',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.AddField(
            model_name='network_suggestions',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AddField(
            model_name='network_suggestions',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AddField(
            model_name='network_suggestions',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.AddField(
            model_name='recommandation_articles',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AddField(
            model_name='recommandation_articles',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AddField(
            model_name='recommandation_articles',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.AddField(
            model_name='recommandation_video',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AddField(
            model_name='recommandation_video',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AddField(
            model_name='recommandation_video',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
    ]
