# Generated by Django 3.1.4 on 2021-01-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0064_auto_20210119_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='company_size',
            field=models.CharField(choices=[('MC', 'Micro'), ('SM', 'Small'), ('MD', 'Medium')], default='SM', max_length=5),
        ),
    ]
