# Generated by Django 3.1.4 on 2021-01-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0065_user_profile_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_asset',
            name='max_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag_asset',
            name='min_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag_cash',
            name='max_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag_cash',
            name='min_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag_liquidity',
            name='max_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag_liquidity',
            name='min_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag_profit',
            name='max_result',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tag_profit',
            name='min_result',
            field=models.FloatField(default=0.0),
        ),
    ]
