# Generated by Django 3.1.4 on 2021-01-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0066_auto_20210121_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='profit_tag',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='profit_tag',
            field=models.ManyToManyField(default=1, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
    ]
