# Generated by Django 3.1.4 on 2021-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0067_auto_20210121_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='asset_tag',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='asset_tag',
            field=models.ManyToManyField(default=1, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
    ]
