# Generated by Django 3.1.4 on 2021-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0068_auto_20210121_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='cash_tag',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='cash_tag',
            field=models.ManyToManyField(default=1, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
    ]
