# Generated by Django 3.1.4 on 2021-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0069_auto_20210121_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='liquidity_tag',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='liquidity_tag',
            field=models.ManyToManyField(default=1, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
    ]
