# Generated by Django 3.1.4 on 2021-01-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0071_auto_20210122_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='q1_net_cash_flow',
            field=models.FloatField(default=0, verbose_name='Q1 Net Cash Flow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='q2_net_cash_flow',
            field=models.FloatField(default=0, verbose_name='Q2 Net Cash Flow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='q3_net_cash_flow',
            field=models.FloatField(default=0, verbose_name='Q2 Net Cash Flow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_financial_data_v2',
            name='q4_net_cash_flow',
            field=models.FloatField(default=0, verbose_name='Q2 Net Cash Flow'),
            preserve_default=False,
        ),
    ]
