# Generated by Django 3.1.4 on 2021-01-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0074_auto_20210125_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network_suggestions',
            name='asset_tag',
        ),
        migrations.AddField(
            model_name='network_suggestions',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.RemoveField(
            model_name='network_suggestions',
            name='cash_tag',
        ),
        migrations.AddField(
            model_name='network_suggestions',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.RemoveField(
            model_name='network_suggestions',
            name='liquidity_tag',
        ),
        migrations.AddField(
            model_name='network_suggestions',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.RemoveField(
            model_name='network_suggestions',
            name='profit_tag',
        ),
        migrations.AddField(
            model_name='network_suggestions',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
        migrations.RemoveField(
            model_name='recommandation_articles',
            name='asset_tag',
        ),
        migrations.AddField(
            model_name='recommandation_articles',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.RemoveField(
            model_name='recommandation_articles',
            name='cash_tag',
        ),
        migrations.AddField(
            model_name='recommandation_articles',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.RemoveField(
            model_name='recommandation_articles',
            name='liquidity_tag',
        ),
        migrations.AddField(
            model_name='recommandation_articles',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.RemoveField(
            model_name='recommandation_articles',
            name='profit_tag',
        ),
        migrations.AddField(
            model_name='recommandation_articles',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
        migrations.RemoveField(
            model_name='recommandation_video',
            name='asset_tag',
        ),
        migrations.AddField(
            model_name='recommandation_video',
            name='asset_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.RemoveField(
            model_name='recommandation_video',
            name='cash_tag',
        ),
        migrations.AddField(
            model_name='recommandation_video',
            name='cash_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.RemoveField(
            model_name='recommandation_video',
            name='liquidity_tag',
        ),
        migrations.AddField(
            model_name='recommandation_video',
            name='liquidity_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.RemoveField(
            model_name='recommandation_video',
            name='profit_tag',
        ),
        migrations.AddField(
            model_name='recommandation_video',
            name='profit_tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
    ]
