# Generated by Django 3.1.4 on 2021-01-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0076_auto_20210125_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network_suggestions',
            name='asset_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='network_suggestions',
            name='cash_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AlterField(
            model_name='network_suggestions',
            name='liquidity_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.AlterField(
            model_name='network_suggestions',
            name='profit_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
        migrations.AlterField(
            model_name='recommandation_articles',
            name='asset_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='recommandation_articles',
            name='cash_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AlterField(
            model_name='recommandation_articles',
            name='liquidity_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.AlterField(
            model_name='recommandation_articles',
            name='profit_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
        migrations.AlterField(
            model_name='recommandation_video',
            name='asset_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_asset', verbose_name='Asset Tag'),
        ),
        migrations.AlterField(
            model_name='recommandation_video',
            name='cash_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_cash', verbose_name='Cash Tag'),
        ),
        migrations.AlterField(
            model_name='recommandation_video',
            name='liquidity_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_liquidity', verbose_name='Liquidity Tag'),
        ),
        migrations.AlterField(
            model_name='recommandation_video',
            name='profit_tag',
            field=models.ManyToManyField(default=[0], to='Maia.tag_profit', verbose_name='Profit Tag'),
        ),
    ]
