# Generated by Django 3.1.4 on 2021-01-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0078_qualitative_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualitative_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('min_result', models.FloatField(default=0.0)),
                ('max_result', models.FloatField(default=0.0)),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
            ],
        ),
    ]
