# Generated by Django 3.1.4 on 2021-01-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0079_qualitative_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommandation_articles',
            name='qualitative_tag',
            field=models.ManyToManyField(default=[0], to='Maia.qualitative_tag', verbose_name='Qualitative Tag'),
        ),
    ]
