# Generated by Django 3.1.4 on 2021-01-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0081_auto_20210126_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='network_suggestions',
            name='qualitative_tag',
            field=models.ManyToManyField(default=[0], to='Maia.qualitative_tag', verbose_name='Qualitative Tag'),
        ),
    ]
