# Generated by Django 3.1.4 on 2021-01-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0082_network_suggestions_qualitative_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advices',
            name='qualitative_tag',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='qualitative_tag',
        ),
    ]
