# Generated by Django 3.1.4 on 2021-01-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0083_auto_20210126_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='advices',
            name='qualitative_tag',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='Maia.qualitative_tag', verbose_name='Liquidity Tag'),
        ),
    ]
