# Generated by Django 3.1.4 on 2021-01-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0085_auto_20210126_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='qualitative_tag',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='Maia.qualitative_tag', verbose_name='Qualitative Tag'),
        ),
    ]
