# Generated by Django 3.1.4 on 2021-01-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Maia', '0086_user_profile_qualitative_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualitative_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set1q1', models.FloatField()),
                ('set1q2', models.FloatField()),
                ('set1q3', models.FloatField()),
                ('set1q4', models.FloatField()),
                ('set1q5', models.FloatField()),
                ('set2q1', models.FloatField()),
                ('set2q2', models.FloatField()),
                ('set2q3', models.FloatField()),
                ('set2q4', models.FloatField()),
                ('set2q5', models.FloatField()),
                ('set3q1', models.FloatField()),
                ('set3q2', models.FloatField()),
                ('set3q3', models.FloatField()),
                ('set3q4', models.FloatField()),
                ('set3q5', models.FloatField()),
                ('set4q1', models.FloatField()),
                ('set4q2', models.FloatField()),
                ('set4q3', models.FloatField()),
                ('set4q4', models.FloatField()),
                ('set4q5', models.FloatField()),
                ('set5q1', models.FloatField()),
                ('set5q2', models.FloatField()),
                ('set5q3', models.FloatField()),
                ('set5q4', models.FloatField()),
                ('set5q5', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maia.user_profile')),
            ],
        ),
    ]
